pluginGroup=com.github.reactunitconverter
pluginName=ReactUnitConverter
pluginVersion=1.0.0

platformType=IU
platformVersion=2023.2
platformDownloadSources=true

javaVersion=17
gradleVersion=8.14.5

kotlinCodeStyle=official

org.gradle.jvmargs=-Xmx3g -XX:MaxMetaspaceSize=1g
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.java.home=/tmp/tools/jdk-17
